### ISSUE TITLE
Feature Request: toggle deadline changes so as to not interfere with other mods

### ISSUE THREAD

**Issue by DJFarr** [Lordfirespeed/Lethal-Company-Augmented-Enhancer#1]
Hi,
As mentioned in the title, ability to toggle the deadline overrides on or off, so that other mods can take over that job.
Thanks

**Comment by DJFarr** [comment]
an afterthought - it might make sense to be able to toggle every feature on or off, not just that one.

**Comment by Lordfirespeed** [comment]
Days per quota feature flag is implemented on main as of 64c4113eb

Most features have their own flag. 
All features will have their own flag eventually
