### ISSUE TITLE
Mod is seemingly nonfunctional even when loaded by itself.

### ISSUE THREAD

**Issue by Darkmega18** [Lordfirespeed/Lethal-Company-Augmented-Enhancer#24]
Will you be updating the mod soon? It is currently nonfunctional for me. After testing with other mods and without other mods. The money over time etc all don't seem to be taking effect. I still start with 60 credits when it's set to 100, and my quota still starts around 130 instead of the 100 I set.

**Comment by Darkmega18** [comment]
After moving it to higher in the mod list and disabling delegation it starting working, but then my terminal became broken. 

With your showterminal setting on I get stuck in the terminal unable to get out of it with any input. When the terminal was off I'd try to use the terminal but nothing would happen and the prompt would go away making it nonfunctional. :V

**Comment by Darkmega18** [comment]
[Default_1702400070984.zip](https://github.com/Lordfirespeed/Lethal-Company-Augmented-Enhancer/files/13651062/Default_1702400070984.zip)
state of my current modpack for testing if you get to it.

**Comment by Lordfirespeed** [comment]
The zipfile you've provided doesn't even have this mod installed.

**Comment by Lordfirespeed** [comment]
I can't reproduce this issue with the latest (development) version of the mod.

Once released, if you're still having problems, please let me know here! if not, please close issue.
